name: FlipSide
options:
  bundleIdPrefix: com.flipside
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en

targets:
  FlipSide:
    type: application
    platform: iOS
    configFiles:
      Debug: FlipSide/Config/AppConfig.xcconfig
      Release: FlipSide/Config/AppConfig.xcconfig
    sources:
      - FlipSide
    info:
      path: FlipSide/Info.plist
      properties:
        CFBundleDisplayName: Flip Side
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        CFBundleURLTypes:
          - CFBundleURLName: com.flipside.oauth
            CFBundleURLSchemes:
              - flipside
        DiscogsConsumerKey: $(DISCOGS_CONSUMER_KEY)
        DiscogsConsumerSecret: $(DISCOGS_CONSUMER_SECRET)
        UILaunchScreen: {}
        NSCameraUsageDescription: "Flip Side needs camera access to scan vinyl record labels and covers."
        NSPhotoLibraryUsageDescription: "Flip Side needs photo library access to let you select existing photos of vinyl records."
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.flipside.FlipSide
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.9"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        TARGETED_DEVICE_FAMILY: "1"  # iPhone only
        ENABLE_PREVIEWS: YES

  FlipSideTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - FlipSideTests
    dependencies:
      - target: FlipSide
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.flipside.FlipSideTests
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGNING_ALLOWED: NO
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/FlipSide.app/FlipSide"
        BUNDLE_LOADER: "$(TEST_HOST)"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
